<?php

namespace AppBundle\Repository;

/**
 * MainSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainSliderRepository extends \Doctrine\ORM\EntityRepository
{
}
