<?php

namespace AppBundle\Repository;

/**
 * ProductLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
