<?php

namespace AppBundle\Repository;

/**
 * RewardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RewardsRepository extends \Doctrine\ORM\EntityRepository
{
}
