services:
    app.admin.main_slider:
        class: AppBundle\Admin\MainSliderAdmin
        arguments: [~, AppBundle\Entity\MainSlider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Основной Слайдер }
