services:
    app.admin.main_slider:
        class: AppBundle\Admin\MainSliderAdmin
        arguments: [~, AppBundle\Entity\MainSlider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Основной Слайдер }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Продукция }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Категории }

    app.admin.product_link:
        class: AppBundle\Admin\ProductLinkAdmin
        arguments: [~, AppBundle\Entity\ProductLink, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Тип }

    app.admin.product_has_media:
            class: AppBundle\Admin\ProductHasMediaAdmin
            arguments: [~, AppBundle\Entity\ProductHasMedia, AppBundle:ProductHasMediaAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Контент, label: Изображения продукции, show_in_dashboard: false}

    app.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Статьи }

    app.admin.article_has_media:
            class: AppBundle\Admin\ArticleHasMediaAdmin
            arguments: [~, AppBundle\Entity\ArticleHasMedia, AppBundle:ArticleHasMediaAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Контент, label: Изображения статей, show_in_dashboard: false}

    app.admin.rewards:
        class: AppBundle\Admin\RewardsAdmin
        arguments: [~, AppBundle\Entity\Rewards, AppBundle:RewardsAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: О нас - Награды }

    app.admin.rewards_has_media:
            class: AppBundle\Admin\RewardsHasMediaAdmin
            arguments: [~, AppBundle\Entity\RewardsHasMedia, AppBundle:RewardsHasMediaAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Контент, label: Награды, show_in_dashboard: false}
