services:
    app.admin.main_slider:
        class: AppBundle\Admin\MainSliderAdmin
        arguments: [~, AppBundle\Entity\MainSlider, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Основной Слайдер }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Продукция }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Категории }

    app.admin.product_link:
        class: AppBundle\Admin\ProductLinkAdmin
        arguments: [~, AppBundle\Entity\ProductLink, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Тип }

    app.admin.product_has_media:
            class: AppBundle\Admin\ProductHasMediaAdmin
            arguments: [~, AppBundle\Entity\ProductHasMedia, AppBundle:ProductHasMediaAdmin]
            tags:
                - {name: sonata.admin, manager_type: orm, group: Контент, label: Изображения продукции, show_in_dashboard: false}